# Generated by Django 4.2.3 on 2023-07-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_carta", models.PositiveIntegerField(db_index=True)),
                ("nombre", models.CharField(max_length=200)),
                ("mazo", models.CharField(max_length=200)),
                ("pinta", models.CharField(max_length=50)),
                ("numero", models.IntegerField()),
                ("descripcion", models.TextField()),
                ("publicado", models.DateTimeField(blank=True, null=True)),
                ("imagen", models.ImageField(upload_to="")),
            ],
        ),
    ]
