# Generated by Django 4.2.3 on 2023-07-27 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carta", "0002_carta_arcano"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carta",
            options={"ordering": ["numero"]},
        ),
    ]
